#!/usr/bin/env bash
# configure web-02 to be identical to web-01.

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/My404File.html
sed -i '/root \/var\/www\/html;/a error_page 404 /My404File.html;' /etc/nginx/sites-available/default

sed -i '/root /var/www/html;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
