#!/usr/bin/env bash
# Install and configure HAproxy

balancer="\
frontend FronFron
    bind *:80
    mode http
    default_backend BackBack

backend BackBack
    balance roundrobin
    server 381246-web-01 52.91.119.108:80 check
    server 381246-web-02 100.25.138.20:80 check
"

# Update the sys
sudo apt-get -y update

# Install haproxy
sudo apt-get -y install haproxy

# Start the service
sudo service haproxy start

cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg

# restart the service
sudo service haproxy restart
